# -*- coding: utf-8 -*-
"""Env_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/bing0037/Jupyter_test/blob/master/Env_test.ipynb

# Online Environment
"""

import tensorflow as tf
tf.__version__

import keras
keras.__version__

"""# Run system commands in Jupyter notebook by prefacing them with a ! character"""

!ls

!mkdir -p src/test
!ls

import sys
!{sys.executable} --version